module.exports = {
    Team: { SPECTATORS: 0, RED: 1, BLUE: 2 },
    State: { PLAY: 0, PAUSE: 1, STOP: 2 },
    Role: { PLAYER: 0, VIP: 1, ADMIN_TEMP: 2, ADMIN_PERM: 3, MASTER: 4 },
    HaxNotification: { NONE: 0, CHAT: 1, MENTION: 2 },
    Situation: { STOP: 0, KICKOFF: 1, PLAY: 2, GOAL: 3 },
    welcomeColor: 0xc4ff65,
    announcementColor: 0xffefd6,
    infoColor: 0xbebebe,
    privateMessageColor: 0xffc933,
    redColor: 0xff4c4c,
    blueColor: 0x62cbff,
    warningColor: 0xffa135,
    errorColor: 0xa40000,
    successColor: 0x75ff75,
    defaultColor: null,
    masterChatColor: 0xffd700,
    adminChatColor: 0x00bfff,
    vipChatColor: 0xc77dff,
};
